config/routes.rb
SnippetMarketplace::Application.routes.draw do
  resources :snippets

  devise_for :users
  mount Afterparty::Engine, at: "afterparty", as: "afterparty_engine"
  root 'snippets#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, Snippet, user_id: user.id
    can :read, Snippet
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :code, :user_id, :language
  attr_accessible :title, :price, :code, :language, :description

  scope :search, -> (title) { where("lower(title) LIKE ?", "%#{title.downcase}%") }

  def syntaxed_code
    CodeRay.scan("\n#{code}", language).div(:css => :class).html_safe
  end

  def human_price
    return "Free" if price == 0
    "<i class='fa fa-bitcoin'></i> #{price}".html_safe
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :snippets

  attr_accessible :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  load_and_authorize_resource

  has_scope :search
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = apply_scopes(Snippet).all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = current_user.snippets.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @snippet }
      else
        format.html { render action: 'new' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end

  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:code, :title, :price, :language, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_element form, name, element, label_name=nil, opts={}
    label_name ||= name.to_s.humanize
    if opts.class == Hash
      unless opts[:class]
        opts[:class] = "form-control"
      end
      if element == :text_area
        if !opts[:rows]
          opts.merge!(rows: 4)
        end
      end
    end
    html = '<div class="form-group">'
    if form.nil?
      html << send(:label, name, label_name, class: 'control-label col-sm-2')
    else
      html << form.send(:label, name, label_name, class: 'control-label col-sm-2')
    end
    html << '<div class="col-sm-8">'
    if form.nil?
      html << send(element.to_s+"_tag", name, nil, opts)
    else
      html << form.send(element, name, opts)
    end
    html << '</div></div>'
    html.html_safe
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      - if content_for? :title
        = yield(:title)
        = " - "
      Snippet Marketplace
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = favicon_link_tag
    = yield(:head)

  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container-fluid

        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} Snippet Central

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
          %ul.nav.navbar-nav.navbar-right
            %form.navbar-form.navbar-left{role: "search"}
              .form-group
                = form_tag "/", method: :get do
                  = text_field_tag :search, params[:search], placeholder: "Search Code Snippets", class: 'form-control'
                  %button.btn.btn-default{type: "submit"} Search
            - if user_signed_in?
              %li.dropdown
                = link_to "#", class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
                  = current_user.email
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign Up", new_user_registration_path
              %li
                = link_to "Log In", new_user_session_path

    - if notice
      .alert.alert-success= notice
    - if alert
      .alert.alert-danger= alert
    .container
      = yield
    %footer.container
      %hr
      %p © 2014 Snippet Marketplace

app/views/snippets/_form.html.haml
= form_for @snippet, html: { class: "form-horizontal" } do |f|
  - if @snippet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@snippet.errors.count, "error")} prohibited this snippet from being saved:"
      %ul
        - @snippet.errors.full_messages.each do |msg|
          %li= msg
  = form_element f, :title, :text_field
  = form_element f, :code, :text_area
  = form_element f, :price, :text_field

  = form_element f, :language, :text_field
  = form_element f, :description, :text_area

  .actions
    = f.submit (@snippet.new_record? ? 'Create' : 'Update'), class: 'btn btn-success'

app/views/snippets/edit.html.haml
%h1 Editing snippet

= render 'form'

= link_to 'Show', @snippet
\|
= link_to 'Back', snippets_path

app/views/snippets/index.html.haml
.text-center
  %h1 A Marketplace for Code Snippets
  %br
  %br

%table.table
  %tr
    %th Title
    %th Price
    %th Language
    %th

  - @snippets.each do |snippet|
    %tr
      %td= link_to snippet.title, snippet
      %td= snippet.price
      %td= snippet.language
      %td
        .btn-group
          = link_to 'Edit', edit_snippet_path(snippet), class: 'btn btn-default btn-xs'
          = link_to 'Destroy', snippet, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs'

%br

= link_to fa_icon(:plus, text: "New Snippet"), new_snippet_path, class: 'btn btn-primary'

app/views/snippets/new.html.haml
%h1 New snippet

= render 'form'

= link_to 'Back', snippets_path

app/views/snippets/show.html.haml
%h1= @snippet.title
%h5
  By
  = @snippet.user.email
  %span.label.label-primary= @snippet.language
= @snippet.syntaxed_code
%h4
  %b Price:
  = @snippet.human_price
- unless @snippet.description.blank?
  .well
    %p
      %strong Description
    %p= @snippet.description

.btn-group
  - if can? :manage, @snippet
    = link_to 'Edit', edit_snippet_path(@snippet), class: 'btn btn-default'
  = link_to 'Back', snippets_path, class: 'btn btn-default'